import * as React from 'react';
import { View, Text, Pressable } from 'react-native';
import { Badge } from './ui/badge';
import { MarkdownBody } from './MarkdownBody';
import { useVulnRecommendations } from '../hooks/useVulnRecommendations';

const SUBSECTIONS = [
  { key: 'prevention',     glyph: '◆', label: 'HOW TO PREVENT' },
  { key: 'considerations', glyph: '◐', label: "WHAT TO CONSIDER" },
  { key: 'remediation',    glyph: '⚠', label: "IF YOU'RE AFFECTED" },
];

function SkeletonBar({ width = 'w-full' }) {
  return <View className={`bg-ink/10 h-3 ${width} mb-2`} />;
}

function SubsectionSkeleton({ glyph, label }) {
  return (
    <View className="px-4 lg:px-6 py-3 border-t border-divider">
      <View className="flex-row items-center gap-2 mb-2">
        <Text className="font-mono-bold text-[10px] text-ink">{glyph}</Text>
        <Text className="font-mono-bold text-[10px] text-ink uppercase tracking-eyebrow">{label}</Text>
      </View>
      <SkeletonBar />
      <SkeletonBar width="w-11/12" />
      <SkeletonBar width="w-4/5" />
    </View>
  );
}

function Subsection({ glyph, label, body }) {
  return (
    <View className="px-4 lg:px-6 py-3 border-t border-divider">
      <View className="flex-row items-center gap-2 mb-2">
        <Text className="font-mono-bold text-[10px] text-ink">{glyph}</Text>
        <Text className="font-mono-bold text-[10px] text-ink uppercase tracking-eyebrow">{label}</Text>
      </View>
      <MarkdownBody>{body}</MarkdownBody>
    </View>
  );
}

/**
 * AI-generated remediation guidance for a single vulnerability.
 *
 * @param {{
 *   vuln: import('../services/osv').NormalizedVuln,
 *   packageInfo: { name: string, ecosystem: string }
 * }} props
 */
export function VulnRecommendations({ vuln, packageInfo }) {
  const { data, error, isLoading, mutate } = useVulnRecommendations(vuln, packageInfo);

  return (
    <View className="border-t-2 border-ink">
      <View className="flex-row items-center justify-between px-4 lg:px-6 py-3">
        <Text className="font-mono-bold text-[10px] text-ink uppercase tracking-eyebrow">
          AI Recommendations
        </Text>
        <Badge variant="outline" size="sm">AI · BETA</Badge>
      </View>

      {isLoading && !data && SUBSECTIONS.map(s => (
        <SubsectionSkeleton key={s.key} glyph={s.glyph} label={s.label} />
      ))}

      {error && !data && (
        <View className="px-4 lg:px-6 py-4 border-t border-divider">
          <Text className="font-mono-bold text-[10px] text-critical uppercase tracking-eyebrow mb-2">
            Could not generate recommendations
          </Text>
          <Text className="font-mono text-xs text-muted mb-3" numberOfLines={2}>
            {String(error?.message ?? error)}
          </Text>
          <Pressable
            onPress={() => mutate()}
            accessibilityRole="button"
            className="self-start border-2 border-ink px-3 py-1 web:cursor-pointer hover:bg-ink/5 active:bg-ink/10"
          >
            <Text className="font-mono-bold text-xs text-ink uppercase tracking-widest">
              RETRY ↻
            </Text>
          </Pressable>
        </View>
      )}

      {data && SUBSECTIONS.map(s => (
        <Subsection key={s.key} glyph={s.glyph} label={s.label} body={data[s.key]} />
      ))}

      {data && (
        <View className="px-4 lg:px-6 py-2 border-t border-divider">
          <Text className="font-mono text-[10px] text-muted">
            Generated by AI — verify before acting on production systems.
          </Text>
        </View>
      )}
    </View>
  );
}
